export const TOGGLE_MENU = 'GLOBAL/IS_MENU_OPENED'

export const SHAW_LOG_IN = 'GLOBAL/SHAW_LOG_IN'
export const HIDE_LOG_IN = 'GLOBAL/HIDE_LOG_IN'

export const SHAW_SING_UP = 'GLOBAL/SHAW_SING_UP'
export const HIDE_SING_UP = 'GLOBAL/HIDE_SING_UP'

export const SET_USER = 'USER/SET_USER'
export const SET_FIND_USER = 'USER/SET_FIND_USER'
export const SET_WHAT_OPEN = 'USER/SET_WHAT_OPEN'
export const LOGOUT = 'USER/LOGOUT'
export const CHANGE_INPUT = 'USER/CHANGE_INPUT'
export const HOME_PAGE_TEXTS = 'USER/HOME_PAGE_TEXTS'

export const UPDATE_USERS = 'USER/UPDATE_USERS'

export const FETCH_ALL_USERS = 'ADMIN/FETCH_ALL_USERS'
export const FETCH_ALL_TEXT_MAIN = 'ADMIN/FETCH_ALL_TEXT_MAIN'

export const FETCH_REQUESTS_ID = 'ADMIN/FETCH_REQUESTS_ID'





